### ISSUE TITLE
Input history not sending correct command

### ISSUE THREAD

**Issue by thedandroid** [shawncplus/neuro#1]
When pressing up or down in the input box, the input box value correctly scrolls through the input history; but, upon pressing enter, only the last command entered is sent if the option for highlighting last command is on, or nothing at all if that option isn't set.

**Comment by shawncplus** [comment]
Yeah this should be an easy fix. Looks like in this history stuff I'm manually setting `this.$.input.value` which isn't propagating the change notification to `this.input`. Will fix it during lunch
